org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.code.style=official
# TODO: Change me later.
trestle.curseforge.apiKey=$2a$10$wuAJuNZuted3NORVmpgUC.m8sI.pv1tOPKZyBgLFGjxFp/br0lZCC
trestle.version=0.1.7
trestle.versionCode=1007
